
# CẤU HÌNH SERVER & ỨNG DỤNG
server.port=8080
spring.application.name=MarcusStore

# CẤU HÌNH KẾT NỐI SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MarcusStoreDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Pool kết nối (HikariCP) để tối ưu hiệu năng chịu tải
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# CẤU HÌNH JPA / HIBERNATE
# 'validate' kiểm tra tính khớp nhau giữa Entity và DB, tránh việc tự ý thay đổi cấu hình DB vật lý từ code
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Hiển thị và định dạng câu lệnh SQL chạy ngầm ra Console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=false

# Kích hoạt tính năng tải chậm (Lazy Loading) tối ưu bộ nhớ
spring.jpa.open-in-view=false


# CẤU HÌNH ĐỊNH DẠNG DỮ LIỆU JSON (JACKSON)
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss